site_name: Vbox

theme: readthedocs

site_author: Sebastian Baum

repo_url: https://github.com/sebbaum/vbox-docu

nav:
  - Introduction: index.md
  - Prerequisites: prerequisites.md
  - Quickstart: quickstart.md
  - Configuration: configuration.md
  - Webservers: webservers.md
  - PHP: php.md
  - Node: node.md
  - Frameworks: frameworks.md
  - Docker: docker.md
  - Mysql: mysql.md
  - Memcached: memcached.md
  - Redis: redis.md

markdown_extensions:
  - admonition
