site_name: Vbox - v1.8.0

theme: readthedocs

site_author: Sebastian Baum

nav:
  - Introduction: index.md
  - Prerequisites: prerequisites.md
  - Quickstart: quickstart.md
  - Configuration: configuration.md
  - Docker: docker.md

markdown_extensions:
  - admonition
